import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Mail, Zap, Shield } from "lucide-react"

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b px-4 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <span className="font-semibold text-lg tracking-tight">OutreachAI</span>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">Sign in</Button>
            </Link>
            <Link href="/register">
              <Button size="sm">Get started free</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-5xl mx-auto px-4 pt-24 pb-16 text-center">
        <Badge variant="secondary" className="mb-6">Powered by Claude AI</Badge>
        <h1 className="text-5xl font-bold tracking-tight leading-tight mb-6">
          Cold outreach that actually<br />sounds human
        </h1>
        <p className="text-muted-foreground text-xl max-w-2xl mx-auto mb-10">
          Connect your Gmail, describe your niche, and get personalized outreach emails
          generated by AI — sent directly from your own account in seconds.
        </p>
        <Link href="/register">
          <Button size="lg" className="px-8">
            Start for free
          </Button>
        </Link>
      </section>

      {/* Steps */}
      <section className="max-w-5xl mx-auto px-4 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
              <Shield className="w-5 h-5 text-primary" />
            </div>
            <h3 className="font-semibold">1. Connect Gmail</h3>
            <p className="text-sm text-muted-foreground">
              Authorize with your Google account using secure OAuth. We only request send permission — never read access.
            </p>
          </div>
          <div className="text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
              <Zap className="w-5 h-5 text-primary" />
            </div>
            <h3 className="font-semibold">2. Describe your niche</h3>
            <p className="text-sm text-muted-foreground">
              Tell us your service and who you&apos;re targeting. Claude generates a personalized, non-generic email in seconds.
            </p>
          </div>
          <div className="text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
              <Mail className="w-5 h-5 text-primary" />
            </div>
            <h3 className="font-semibold">3. Send &amp; track</h3>
            <p className="text-sm text-muted-foreground">
              Review the email, send it directly from your Gmail account, and track everything in your dashboard.
            </p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-5xl mx-auto px-4 py-16 text-center border-t">
        <h2 className="text-3xl font-bold mb-4">Ready to send better outreach?</h2>
        <p className="text-muted-foreground mb-8">No credit card required. Free to try.</p>
        <Link href="/register">
          <Button size="lg">Get started free</Button>
        </Link>
      </section>
    </div>
  )
}
